######################################################################
# Automatically generated by qmake (1.07a) Sat Mar 12 17:38:13 2005
######################################################################

TEMPLATE = app
CONFIG -= moc
INCLUDEPATH += .

# Input
SOURCES += main.cpp
