# ----------------------------------------------------------
# app project generated by QMsNet (save function)
# ----------------------------------------------------------
TEMPLATE  = app
LANGUAGE  = C++

CONFIG	 += qt warn_on

OBJECTS_DIR = tmp\obj
MOC_DIR     = tmp\moc

SOURCES   =  \
	main.cpp
